name: build-test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: "bash"

env:
  DOTNET_VERSION: "6.0.x"

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out"
        uses: actions/checkout@v3

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: "Install Dependencies"
        run: dotnet restore
      
      - name: "Build"
        run: dotnet build -c ${{ matrix.configuration }} --no-restore

      - name: "Test"
        run: dotnet test -c ${{ matrix.configuration }} --no-build --verbosity normal

      - name: "Publish .NET application"
        if: ${{ matrix.configuration == 'Release' }}
        run: dotnet publish -c ${{ matrix.configuration }} -o ./publish ./src/MaaCopilotServer.Api
