name: publish-docker
on:
  release:
    types: [ published ]

defaults:
  run:
    shell: "bash"

jobs:
  publish-docker:
    runs-on: ubuntu-20.04
    steps:
      - name: "Check out"
        uses: actions/checkout@v2

      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker BuildX"
        uses: docker/setup-buildx-action@v1

      - name: "Setup .NET SDK"
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
          
      - name: "Echo current version number"
        run: echo "Current version is ${{ github.event.release.tag_name }}"

      - name: "Publish .NET application"
        run: dotnet publish -c Release -o ./publish ./src/MaaCopilotServer.Api
        
      - name: "Post publish .NET application"
        run: rm ./publish/*.pdb ./publish/*.Development.json
      
      - name: "Build Docker image"
        run: ./build-docker.sh ${{ github.event.release.tag_name }}

      - name: "Login to Docker Hub"
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push image to Docker Hub"
        run: ./push-docker.sh ${{ github.event.release.tag_name }} ${{ secrets.DOCKERHUB_USERNAME }}
